{% set name = "symfc" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/symfc-{{ version }}.tar.gz
  sha256: 2573f9d106b0d2d930802a91980e60dac056ab168ff51c68dfde9081eea43d9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - spglib

test:
  imports:
    - symfc
  source_files:
    - tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/symfc/symfc
  description: |
    Symfc is a software designed to compute force constants from
    displacement-force datasets in the supercell approach, ensuring they meet
    the required symmetry constraints.
  summary: This is the symfc module.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
